version: 2.1

executors:
  build-executor:
    docker:
      - image: cimg/openjdk:8.0
        environment:
          MAVEN_OPTS: -Xmx1g

workflows:
  build-deploy:
    jobs:
      - build

jobs:
  build:
    executor: build-executor
    steps:
      - checkout
      - run:
          name: Run the tests
          command: |
            mvn -DskipITs=false clean install
            zip -r ~/osgi-jaxrs-connector.zip ~/.m2/repository/com/eclipsesource 
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/target/failsafe-reports/.*xml" -exec cp {} ~/junit/ \;
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - store_test_results:
          path: ~/junit
      - persist_to_workspace:
          root: ~/
          paths:
            - project
      - store_artifacts:
          path: ~/osgi-jaxrs-connector.zip
          destination: osgi-jaxrs-connector.zip
